﻿USE [ExcessInventoryManagement]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sales](
	[SalesId] [int] IDENTITY(1,1) NOT NULL,
	[MarkdownPlanId] [int] NULL,
	[SalesData] [varchar](1000) NULL,
 CONSTRAINT [PK_Sales] PRIMARY KEY CLUSTERED
(
	[SalesId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Sales]  WITH NOCHECK ADD  CONSTRAINT [FK_Sales_MarkdownPlan] FOREIGN KEY([MarkdownPlanId])
REFERENCES [dbo].[MarkdownPlan] ([MarkdownPlanId])
GO